wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.4
    cli_version: 0.17.5
    framework: huggingface
    huggingface_version: 4.26.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1787065934
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 55
      - 71
      - 83
      - 105
      3:
      - 13
      - 23
      - 61
      4: 3.10.4
      5: 0.17.5
      6: 4.26.1
      8:
      - 5
      13: linux-x86_64
pretrained_model_name_or_path:
  desc: null
  value: CompVis/stable-diffusion-v1-4
revision:
  desc: null
  value: null
max_train_samples:
  desc: null
  value: null
cache_dir:
  desc: null
  value: null
seed:
  desc: null
  value: null
center_crop:
  desc: null
  value: false
random_flip:
  desc: null
  value: false
logging_dir:
  desc: null
  value: logs
mixed_precision:
  desc: null
  value: null
report_to:
  desc: null
  value: wandb
local_rank:
  desc: null
  value: -1
max_train_steps:
  desc: null
  value: 100
gradient_checkpointing:
  desc: null
  value: false
train_data_dir:
  desc: null
  value: ../vangogh2photo/trainA
label_resize_train_data_dir:
  desc: null
  value: ./datasets/syn_vangogh
artist_name:
  desc: null
  value: vangogh
output_dir:
  desc: null
  value: exps/exp_vangogh
resolution:
  desc: null
  value: 512
model_type:
  desc: null
  value: MLP
train_batch_size:
  desc: null
  value: 8
gradient_accumulation_steps:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 1
select:
  desc: null
  value: random
learning_rate:
  desc: null
  value: 0.1
scale_lr:
  desc: null
  value: false
lr_scheduler:
  desc: null
  value: constant
lr_warmup_steps:
  desc: null
  value: 0
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_weight_decay:
  desc: null
  value: 0
adam_epsilon:
  desc: null
  value: 1.0e-08
max_grad_norm:
  desc: null
  value: 1.0
skip_evaluation:
  desc: null
  value: false
log_every_steps:
  desc: null
  value: 1000
log_every_epochs:
  desc: null
  value: 5
prompt:
  desc: null
  value: ''
template_key:
  desc: null
  value: '0'
concept:
  desc: null
  value: null
clip_attributes:
  desc: null
  value: null
num_test_samples:
  desc: null
  value: 2
original_sd:
  desc: null
  value: false
interpolate_type:
  desc: null
  value: ''
interpolate_steps:
  desc: null
  value: null
evaluation_type:
  desc: null
  value: eval
image_dir:
  desc: null
  value: images
prompt_file:
  desc: null
  value: null
src_img_dir:
  desc: null
  value: null
gen_img_dir:
  desc: null
  value: null
kid_subset_size:
  desc: null
  value: 1000
use_sld:
  desc: null
  value: false
use_esd:
  desc: null
  value: false
negative_prompt:
  desc: null
  value: null
scheduler:
  desc: null
  value: ddim
num_inference_steps:
  desc: null
  value: 50
fp16:
  desc: null
  value: false
content_img:
  desc: null
  value: ../vangogh2photo/trainB/
mlp_weight:
  desc: null
  value: 1.5
lambda_c:
  desc: null
  value: 0.9
lambda_s:
  desc: null
  value: 0.9
lambda_g:
  desc: null
  value: 0.9
